FROM ibmfunctions/action-python-v3.7

COPY ./requirements.txt /app/requirements.txt

WORKDIR /app

RUN pip install --user -r requirements.txt

COPY . /app

ENTRYPOINT [ "python" ]

CMD [ "dazzle-scrape.py" ]