FROM python:3.9-alpine

COPY ./requirements.txt /app/requirements.txt

WORKDIR /app

RUN apk --update add python py-pip openssl ca-certificates py-openssl wget bash linux-headers
RUN apk --update add --virtual build-dependencies libffi-dev openssl-dev python-dev py-pip build-base \
  && pip install --upgrade pip \
  && pip install --upgrade pipenv\
  && pip install --upgrade -r /app/requirements.txt\
  && apk del build-dependencies

COPY . /app

ENTRYPOINT [ "python" ]

CMD [ "dazzle-scrape.py" ]


FROM python:3.8.0-slim
RUN apt-get update \
&& apt-get install gcc -y \
&& apt-get clean
COPY requirements.txt /app/requirements.txt
WORKDIR app
RUN pip install --user -r requirements.txt
COPY . /app

--

FROM python:3.8-slim-buster

RUN apt-get update \
&& apt-get install gcc -y \
&& apt-get clean

COPY ./requirements.txt /app/requirements.txt

WORKDIR /app

RUN pip install --user -r requirements.txt

COPY . /app

ENTRYPOINT [ "python" ]

CMD [ "dazzle-scrape.py" ]